[package]
name = "reactive-fn"
version = "0.1.0"
authors = ["frozenlib <frozenlib@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-core = "0.3.21"
slabmap = "0.1.1"
serde = "1.0.139"
either = "1.7.0"
derive-ex = "0.1.1"
rt-local-core = { version = "0.1.0" }

[dev-dependencies]
bincode = "1.3.3"
async-std = "1.12.0"
futures = "0.3.21"
rt-local = { version = "0.1.2" }

[lib]
bench = false
