[package]
name = "reactive-fn"
version = "0.1.0"
authors = ["frozenlib <frozenlib@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
slabmap = "0.1"
serde = "1.0.125"
either = "1.6.1"
derive-ex = "0.1.0"

[dev-dependencies]
bincode = "1.3.3"

[lib]
bench = false
