name: CI

on:
  push:
  pull_request:
  schedule: [cron: "20 5 * * *"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Build tests
        run: cargo test --verbose --no-run
      - name: Run tests
        run: cargo test --verbose
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Clippy
        run: cargo clippy --all-features --tests --lib -- -W clippy::all
        env:
          RUSTFLAGS: -D warnings
      - name: Set minimal versions
        run: cargo +nightly update -Z minimal-versions
      - name: Build tests (minimal versions)
        run: cargo +stable test --verbose --no-run
      - name: Run tests (minimal versions)
        run: cargo +stable test --verbose

      - name: Run benchmark
        if : ${{ github.ref_name == 'master' }}
        run: cargo +nightly bench | tee output.txt
        working-directory: ./reactive-fn-benchmark

      - name: Store benchmark result
        if : ${{ github.ref_name == 'master' }}
        uses: rhysd/github-action-benchmark@v1
        with:
          name: reactive-fn Benchmark
          tool: "cargo"
          fail-on-alert: false
          comment-on-alert: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          output-file-path: ./reactive-fn-benchmark/output.txt
