name: CI

on:
  push:
  pull_request:
  schedule: [cron: "20 5 * * *"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Build tests
        run: cargo test --verbose --no-run
      - name: Run tests
        run: cargo test --verbose
