name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}-3
          restore-keys: ${{ runner.os }}-cargo-registry

      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}-3
          restore-keys: ${{ runner.os }}-cargo-index

      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-build-target-build

      - name: Build
        run: cargo build --verbose --all-features

      - name: Run tests
        run: cargo test --verbose --all-features

  benchmark:
    name: Performance regression check
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}-3
          restore-keys: ${{ runner.os }}-cargo-registry

      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}-3
          restore-keys: ${{ runner.os }}-cargo-index

      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-benchmark-${{ hashFiles('**/Cargo.lock') }}-3
          restore-keys: |
            ${{ runner.os }}-cargo-build-target-build-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-build-target-build

      - name: Run benchmark
        run: cargo +nightly bench | tee output.txt

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: "cargo"
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true

  build-features:
    name: Build each features
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - --features smol
          - --features tokio
          - --features async-std
          -
    steps:
      - uses: actions/checkout@v2

      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}-3
          restore-keys: ${{ runner.os }}-cargo-registry

      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}-3
          restore-keys: ${{ runner.os }}-cargo-index

      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-bf-${{ hashFiles('**/Cargo.lock') }}-${{ matrix.features }}-3
          restore-keys: |
            ${{ runner.os }}-cargo-build-target-bf-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-build-target-build-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-build-target-build

      - name: Build lib
        run: cargo build --verbose ${{ matrix.features }}

      - name: Build tests
        run: cargo test --verbose ${{ matrix.features }} --no-run
